name: flutter_ddd
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_state_notifier: ^0.4.2
  provider: ^4.3.0
  sqflite: ^1.3.1
  state_notifier: ^0.5.0
  uuid: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
